# Get the GCC preinstalled image from Docker Hub
FROM gcc:4.9

# Copy the current folder which contains C++ source code to the Docker image under /usr/src
COPY . /usr/src/sensors

# Specify the working directory
WORKDIR /usr/src/sensors

# Use GCC to compile the Test.cpp source file
RUN g++ *.cpp -I . -o Sensor -std=c++11

# Run the program output from the previous step
CMD ["./Sensor"]