version: '2.0'
services:
  spacef.telemetry:
    build: ./telemetry
    ports:
    - "15002:15002"
    networks:
          spacef:
              ipv4_address: 172.16.238.10
  spacef.sensors:
    build: ./sensors
    links:
    - spacef.telemetry
    networks:
          spacef:
              ipv4_address: 172.16.238.11
networks:
  spacef:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1