version: '2.0'
services:
  spacef.telemetry:
    build: ./telemetry
    ports:
    - "15002:15002"
    networks:
          spacef:
              ipv4_address: 172.16.238.10
  spacef.sensors:
    build: ./sensors
    links:
    - spacef.telemetry
    networks:
          spacef:
              ipv4_address: 172.16.238.11
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
        spacef:
            ipv4_address: 172.16.238.12
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
        spacef:
            ipv4_address: 172.16.238.13
networks:
  spacef:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1

volumes:
  zookeeper_data:
  kafka_data: