version: '2.0'
services:
  spacef.telemetry:
    build: ./telemetry
    ports:
    - "15002:15002"
    networks:
          spacef:
              ipv4_address: 172.16.238.10
  spacef.sensors:
    build: ./sensors
    links:
    - spacef.telemetry
    networks:
          spacef:
              ipv4_address: 172.16.238.11
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.238.12
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  spacef:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1